FROM python:3.10

WORKDIR /myenv

COPY ./requirements.txt /myenv/

RUN pip install --upgrade pip && pip install -r ./requirements.txt

COPY ./myenv/* /myenv/

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

EXPOSE 8000
